### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aravindvnair99** [aravindvnair99/Python#1]
Todo:

- [x] Code of Conduct
- [x] Contributing
- [x] Pull request
- [ ] ReadMe
- [x] License

**Comment by anjaliparmar** [comment]
Hello, 
I'm learning python since 2 months.. and i want to contribute in open source python project.

**Comment by aravindvnair99** [comment]
> Hello,
> I'm learning python since 2 months.. and i want to contribute in open source python project.

@anjaliparmar Thanks for your interest. Feel free to submit a pull request with your code. You will be added to the contributors list automatically.

**Comment by anjaliparmar** [comment]
can you please tell me what work i have to do, i'm new for github..

**Comment by aravindvnair99** [comment]
> can you please tell me what work i have to do, i'm new for github..

@anjaliparmar Sure, no issues. I started this repository as an effort to make Python code available for newcomers and others who want to reference. You can clone the repository and add your code. Once you're done, you could submit a pull request which I'll merge once I've verified the code. Add your code to the "Source Codes Testing" folder. You can learn more about Git with help of [Google](https://www.google.com/search?q=learn+git). Feel free to add any code you wish to contribute. You can read the [README](https://github.com/aravindvnair99/Python) file for some additional information. Feel free to get in touch with me if you need more help. You may contact me [here](https://aravindvnair99.firebaseapp.com)
